# This file contains values from Cookiecutter

default_context:
  project_name: "audio-topic-model"
  project_description: "Micro service for performing topic modeling on audio data."
  organization: "audio-topic-model"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "audio_topic_model"
  email: "benjamin.h.glidden@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
